default:
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
      #- apk update && apk add curl && apk add jq

variables:
  TEST_IMAGE: $CI_REGISTRY_IMAGE:test
  IMAGE_VERSION: $CI_REGISTRY_IMAGE:v_$CI_COMMIT_SHA
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  script:
    - echo $TEXT_SECRET
    - cd docker_weather
    - docker build -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $TEST_IMAGE
    - docker run -d -p 9090:9090 --name test $TEST_IMAGE
    - apk update && apk add curl
    - curl http://172.31.27.104:9090
  after_script:
    - docker rm -f test

upload_final_image:
  stage: deploy
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $IMAGE_VERSION
    - docker tag $TEST_IMAGE $IMAGE_LATEST
    - docker push $IMAGE_VERSION
    - docker push $IMAGE_LATEST


