default:
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $REGISTRY -u $CI_REGISTRY_USER --password-stdin

variables:
  TEST_IMAGE: $CI_REGISTRY_IMAGE:test

build-job:
  stage: build
  script:
    - cd docker_weather
    - docker build -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

