default:
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

variables:
  TEST_IMAGE: $CI_REGISTRY_IMAGE:test

build:
  stage: build
  script:
    - cd docker_weather
    - docker build -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - docker ps
    - docker pull $TEST_IMAGE
    - docker run -d -p 9090:9090 --name test $TEST_IMAGE
    - apk update && apk add curl
    - curl http://172.31.27.104:9090
      #after_script:
      #- docker rm -f test

