default:
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin <<<$CI_REGISTRY_PASSWORD

variables:
  TEST_IMAGE: $CI_REGISTRY_IMAGE:test

build-job:
  stage: build
  script:
    - cd docker_weather
    - docker build -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

