default:
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

variables:
  TEST_IMAGE: $CI_REGISTRY_IMAGE:test
  IMAGE_VERSION: $CI_REGISTRY_IMAGE:v_$CI_COMMIT_SHA
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

job_using_vault:
  id_tokens:
    VAULT_ID_TOKEN:
      aud: http://172.31.21.244
  secrets:
    TEXT_SECRET:
      vault: weatherapp/text/Assignment@kv  # translates to secret `ops/data/production/db`, field `password`
      token: $VAULT_ID_TOKEN

build:
  stage: build
  script:
    - echo $TEXT_SECRET
    - cd docker_weather
    - docker build -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $TEST_IMAGE
    - docker run -d -p 9090:9090 --name test $TEST_IMAGE
    - apk update && apk add curl
    - curl http://172.31.27.104:9090
  after_script:
    - docker rm -f test

deploy:
  stage: deploy
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $IMAGE_VERSION
    - docker tag $TEST_IMAGE $IMAGE_LATEST
    - docker push $IMAGE_VERSION
    - docker push $IMAGE_LATEST


