version: "3.6"
services:
  gitlab-runner:
    container_name: 'gitlab-runner'
    restart: 'always'
    image: 'gitlab/gitlab-runner:latest'
    volumes: 
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './conf:/etc/gitlab-runner'

